# Generated by Django 5.2.8 on 2026-04-30 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("catchPhrase", models.CharField(blank=True, max_length=255)),
                ("bs", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("suite", models.CharField(blank=True, max_length=255)),
                ("zipcode", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
